# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: efff1419643331a37a45a11d5778193ef8ae35aa32c3acb665750a79bc38d90d3f2ad1044f045b10f18b27116f8a1f81eb9fa4651e4a24b7c734c6cb2c4c44bc

test:
  secret_key_base: 01ef03ebe74bbafbe0a0e0ec6160c31732d0680f47de0e4a612dfdd8160a40dd53839e7ddbca9a7e85f3e06b1de3b15774b21f9576ab44e7dfd7c9534c507c9f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
